import { aeonik, helvetica } from "../lib/fonts";
import { cn } from "../lib/utils";
import "./globals.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <body
        className={(cn(aeonik.variable, helvetica.variable), "bg-eerie-black")}
      >
        {children}
      </body>
    </html>
  );
}
